### PR TITLE
SDL version changed from SDL1.2 to SDL2

### PR DESCRIPTION
**Pull request by speedy-software-ch**
You still need to change Build Settings to build against SDL2 *.so / *.dll file.

### CODE REVIEW

**Review by speedy-software-ch — COMMENTED** [review]
test

**Comment by speedy-software-ch** [comment]
hhcgfg

**Comment by speedy-software-ch** [comment]
test2

**Comment by speedy-software-ch** [comment]
hgcgjgcbbc

**Comment by speedy-software** [comment]
yjdbdmdnffbf

**Comment by speedy-software** [comment]
bfbfbdkfbf

**Comment by speedy-software** [comment]
fjdkdkfbf

**Comment by speedy-software** [comment]
hggjbccg

**Comment by speedy-software** [comment]
kkgkgkghlhh

**Comment by speedy-software** [comment]
hhgghbgggccv

**Comment by speedy-software** [comment]
kfjfbfbfffb

**Comment by speedy-software** [comment]
fjdjbrvfbffb

**Comment by speedy-software** [comment]
fjbfbgbbfbdb

**Comment by speedy-software** [comment]
rkfkfbcbfbkfkf

**Comment by speedy-software** [comment]
djdjkdbfbfbr

**Comment by speedy-software** [comment]
jhggjbbvhjhggbhg

**Comment by speedy-software** [comment]
hhfhjjggjjggjcxxhjhc

**Comment by speedy-software** [comment]
fjbffbgbgbfnffk

**Comment by speedy-software** [comment]
djhrkfkfnffbf

**Comment by speedy-software** [comment]
dbfbfbxbfbf

**Comment by speedy-software** [comment]
dbfbfbxbfbf

**Comment by speedy-software** [comment]
jfjevdvdvbrbrkrlfkf

**Comment by speedy-software** [comment]
ghkjccbngfcvbbvc

**Comment by speedy-software** [comment]
ghkjccbngfcvbbvc

**Comment by speedy-software** [comment]
fctcrcrxrx

**Comment by speedy-software** [comment]
xjfjfkgkfyhyihylhx

**Comment by speedy-software** [comment]
fufjffbfbfbxbnfndkf

**Pull request merged**
